using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.EventSystems;

public class CardDrag : MonoBehaviour, IEndDragHandler, IDragHandler, IBeginDragHandler, IPointerEnterHandler, IPointerExitHandler
{
    private Vector3 startPosition;
    private Vector3 hoverScale = new Vector3(1.1f, 1.1f, 1.1f);
    private Vector3 originalScale;

    public GameObject card;
    private GameObject darkness;
    private GameObject slideSpot;



    private bool hovering = false;


    void Start()
    {
        card = gameObject;
        darkness = GameObject.FindGameObjectWithTag("Darkness");
        slideSpot = GameObject.FindGameObjectWithTag("SlideSpot");
        startPosition = transform.position;
        originalScale = transform.localScale;
    }

    void Update()
    {
        transform.localScale = Vector3.Lerp(transform.localScale, hovering ? hoverScale : originalScale, Time.deltaTime * 8);
    }

    public void OnBeginDrag(PointerEventData eventData)
    {
        startPosition = transform.position;
    }

    public void OnDrag(PointerEventData eventData)
    {
        hovering = false;
        Vector3 mousePos = Input.mousePosition;

        darkness.SetActive(true);
        transform.position = new Vector3(mousePos.x, mousePos.y, mousePos.z);
        transform.localScale = Vector3.one;
    }

    public void OnEndDrag(PointerEventData eventData)
    {
        RectTransform slideRect = slideSpot.GetComponent<RectTransform>();

        bool isInSpot = RectTransformUtility.RectangleContainsScreenPoint(slideRect, Input.mousePosition);

        darkness.SetActive(false);
        if (isInSpot)
        {
            CardBase cardBase = GetComponent<CardBase>();
            cardBase.Play();
            Destroy(card);
        }
        else
        {
            transform.position = startPosition;
        }

    }

    public void OnPointerEnter(PointerEventData eventData)
    {
        hovering = true;
    }

    public void OnPointerExit(PointerEventData eventData)
    {
        hovering = false;
    }
}
